# Generated by Django 5.2 on 2025-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='productmoldhistory',
            name='count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
