# Generated by Django 5.2 on 2025-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producthistory_count_productmoldhistory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productmoldhistory',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
